# Generated by Django 4.1.2 on 2024-07-22 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat_signup',
            old_name='First_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='chat_signup',
            old_name='Last_name',
            new_name='last_name',
        ),
    ]
