# Generated by Django 4.1.2 on 2024-07-28 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_rename_first_name_chat_signup_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat_signup',
            name='is_active',
        ),
    ]
