# Generated by Django 4.1.2 on 2024-07-28 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_remove_chat_signup_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat_signup',
            name='role',
            field=models.CharField(default='user', max_length=120),
        ),
    ]
