# Generated by Django 5.1 on 2024-08-30 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_chat_signup_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizations_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gst_no', models.CharField(max_length=16, unique=True)),
                ('Company_name', models.CharField(max_length=50)),
                ('Domain', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=50)),
                ('Pincode', models.CharField(max_length=6, unique=True)),
                ('contact_info', models.CharField(max_length=10, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Chat_signup',
            new_name='signup_data',
        ),
    ]
